language: android
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
	- extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository

	- sys-img-x86-android-26
	- sys-img-armeabi-v7a-android-17