language: android

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-21
	- sys-img-x86-android-26

env:
 global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

	
before_install:
 - chmod +x gradlew
 

script:
  - android list target
  - ./gradlew connectedAndroidTest
 